In [11]:
import numpy as np
import pandas as pd

# 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
# How likely is it that you roll doubles when rolling two dice?
outcomes = [1, 2, 3, 4, 5, 6]
n_sims = 1_000_000

die1 = np.random.choice(outcomes, size=n_sims)#setup to match vice sum.
die2 = np.random.choice(outcomes, size=n_sims)

die1[0:5], die2[0:5]

(array([5, 5, 4, 3, 6]), array([6, 2, 2, 6, 4]))

In [3]:
# probability of rolling doubles
(die1==die2).mean()# 1 die equals the other.

0.166551

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [14]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

nrows = 100_000 #set "nrows" to number of simulations to run
ncols = 8       #"coin flips" -- set "ncols" to number of random events in each simulation

In [16]:
#creates array
flips = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)
#(array of heads("True") & tails("False"), number of coin flips multiplied by the number of simulations to run)
#.reshape puts the data into ows and columns like instead of in a row.
flips #variable

array([[ True, False,  True, ..., False,  True,  True],
       [False, False,  True, ...,  True,  True, False],
       [False,  True,  True, ..., False, False, False],
       ...,
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False,  True,  True],
       [False, False, False, ..., False,  True,  True]])

In [17]:
#convert the above into a df
df = pd.DataFrame(flips)
df.head()

0      1      2      3      4      5      6      7
0   True  False   True   True  False  False   True   True
1  False  False   True   True  False   True   True  False
2  False   True   True  False  False  False  False  False
3   True   True  False  False   True  False   True  False
4   True   True   True  False   True  False   True   True

In [23]:
#add and name columns
df['heads']=df.sum(axis=1)#sums the number of heads("True") across columns i.e. "rows"
df['three_heads']=df.heads == 3#counts the number of heads("True") equal to 3
df['greater_heads']=df.heads >= 3#counts the number of heads("True") greater then to 3
df.head()

0      1      2      3      4      5      6      7  heads  three_heads  \
0   True  False   True   True  False  False   True   True   17.0        False   
1  False  False   True   True  False   True   True  False   14.0        False   
2  False   True   True  False  False  False  False  False    7.0        False   
3   True   True  False  False   True  False   True  False   14.0        False   
4   True   True   True  False   True  False   True   True   20.0        False   

   greater_heads  
0           True  
1           True  
2           True  
3           True  
4           True

In [24]:
df.three_heads.mean()#probability of hitting exactly three heads

0.03143

In [25]:
df.greater_heads.mean()#probability of hitting greater then three heads

0.99627

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [29]:
nrows = 100_000 #number times to run the sim
ncols = 4 #number of columns - 1 per cohort
#individual cohorts 
outcomes = [True, False] #True = data & False = web
#run sim
select = np.random.choice(outcomes, nrows*ncols).reshape(nrows,ncols)
select


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True, False, False],
       ...,
       [ True, False, False,  True],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [30]:
df=pd.DataFrame(select)#create df
df.head()

0      1      2      3
0  False  False  False  False
1  False   True   True   True
2   True   True  False  False
3   True  False  False   True
4  False  False   True  False

In [33]:
#add and name colums
df['billboard']=df.sum(axis=1)#sums the number of "true" and adds the total into the "billboard" column

In [36]:
df['data']=df.billboard==2#based on the equation enters true or false
df.head()

0      1      2      3  billboard   data
0  False  False  False  False          0  False
1  False   True   True   True          3  False
2   True   True  False  False          2   True
3   True  False  False   True          2   True
4  False  False   True  False          1  False

In [37]:
df.data.mean()#probability based on the equation above.

0.37565

# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [38]:
nrows = 100_000 # number of times to run the sim
ncols = 5 # number of occurences
#.normal "generates numbers from a normal distribution with a specified mean and standard deviation"
#"3,1.5" -- "3" is the number of poptarts & "1.5" is the standard deviation
#".astype(int)" changes it to a round number(rounds up).
poptarts = np.random.normal(3,1.5, nrows*ncols).astype(int).reshape(nrows,ncols)
poptarts

array([[3, 3, 2, 1, 2],
       [3, 5, 4, 5, 5],
       [4, 4, 6, 4, 0],
       ...,
       [3, 3, 4, 1, 2],
       [1, 2, 4, 0, 2],
       [2, 3, 0, 2, 2]])

In [39]:
df=pd.DataFrame(poptarts)#create df
df.head()

0  1  2  3  4
0  3  3  2  1  2
1  3  5  4  5  5
2  4  4  6  4  0
3 -1  3  1  3  2
4  1  2  2  5  4

In [40]:
df['bought']=df.sum(axis=1)#totals the values across columns to give me the total potarts bought mon-fri
df['remaining']=df['bought']<17#remaining poptarts on friday
df.head()

0  1  2  3  4  bought  remaining
0  3  3  2  1  2      11       True
1  3  5  4  5  5      22      False
2  4  4  6  4  0      18      False
3 -1  3  1  3  2       8       True
4  1  2  2  5  4      14       True

In [41]:
df.remaining.mean()

0.87955

# 5. Compare Heights:
    -Men have an average height of 178 cm and standard deviation of 8cm.
    -Women have a mean of 170, sd = 6cm.
    -Since you have means and standard deviations, you can use np.random.normal to generate observations.
    -If a man and woman are chosen at random, P(woman taller than man)?

In [42]:
#because there are two sets of heights and standards of deviations. 
#create two variables
male=np.random.normal(178,8,100_000)
female=np.random.normal(170,6,100_000)
#now create df as normal
df = pd.DataFrame({'male': male, 'female': female})
df.head()

male      female
0  181.195155  170.749811
1  166.043120  173.661036
2  188.605237  178.045574
3  179.866107  171.572755
4  171.662900  173.212119

In [43]:
#who's taller....? add and name a new columm with "true" or "false" to the df
df['taller']=df.male<df.female#we are looking for women taller then men
df.head()

male      female  taller
0  181.195155  170.749811   False
1  166.043120  173.661036    True
2  188.605237  178.045574   False
3  179.866107  171.572755   False
4  171.662900  173.212119    True

In [44]:
df.taller.mean()

0.21235

# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [45]:
nrows = 100_000
ncols = 50#number of students

chance = [False for r in range(1, 250)]#setting up the false for the 1 in 250 chance that it WILL fail.
chance.append(True)

installs=np.random.choice(chance, nrows*ncols).reshape(nrows,ncols)
installs

array([[False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [46]:
#build the df
df = pd.DataFrame(installs)
df.head()

0      1      2      3      4      5      6      7      8      9   ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

      40     41     42     43     44     45     46     47     48     49  
0  False  False   True  False  False  False  False  False  False  False  
1  False  False  False  False  False  False  False   True  False  False  
2  False  False  False  False  False  False  False  False  False  False  
3  False  False  False  False  False  False  False  False  False  False  
4  False  False  False  False  False  False  False  False  False  False  

[5 rows x 50 columns]

In [49]:
df['no_error']=df.sum(axis=1)==0#setting the df.sum to equal zero finds all "0's" and returns a TRUE value to caluclate the probability
df.head()

0      1      2      3      4      5      6      7      8      9  ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

      41     42     43     44     45     46     47     48     49  no_error  
0  False   True  False  False  False  False  False  False  False     False  
1  False  False  False  False  False  False   True  False  False     False  
2  False  False  False  False  False  False  False  False  False      True  
3  False  False  False  False  False  False  False  False  False      True  
4  False  False  False  False  False  False  False  False  False     False  

[5 rows x 51 columns]

In [50]:
df.no_error.mean()

0.81871

### 100 students

In [53]:
nrows = 100_000
ncols = 100#number of students

chance = [False for r in range(1, 250)]#setting up the false for the 1 in 250 chance that it WILL fail.
chance.append(True)

installs=np.random.choice(chance, nrows*ncols).reshape(nrows,ncols)
installs

#build the df
df = pd.DataFrame(installs)
df.head()

df['no_error']=df.sum(axis=1)==0
df.head()

df.no_error.mean()

0.66881

### 150 students

In [54]:
nrows = 100_000
ncols = 150#number of students

chance = [False for r in range(1, 250)]#setting up the false for the 1 in 250 chance that it WILL fail.
chance.append(True)

installs=np.random.choice(chance, nrows*ncols).reshape(nrows,ncols)
installs

#build the df
df = pd.DataFrame(installs)
df.head()

df['no_error']=df.sum(axis=1)==0
df.head()

df.no_error.mean()

0.54729

### all 450 students

In [55]:
nrows = 100_000
ncols = 450#number of students

chance = [False for r in range(1, 250)]#setting up the false for the 1 in 250 chance that it WILL fail.
chance.append(True)

installs=np.random.choice(chance, nrows*ncols).reshape(nrows,ncols)
installs

#build the df
df = pd.DataFrame(installs)
df.head()

df['no_error']=df.sum(axis=1)==0
df.head()

df.no_error.mean()

0.16367

# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [56]:
nrows = 100_000
ncols = 3# number of days
outcomes = [True, False] #True = show & False = noshow
#run sim
seen = np.random.choice(outcomes, nrows*ncols, p=[.7,.3]).reshape(nrows,ncols)#note "p" --- "probaibility". It is set at 70/30
seen

array([[ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True],
       ...,
       [False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [57]:
#build the df
df = pd.DataFrame(seen)
df.head()

0      1      2
0  True   True  False
1  True  False   True
2  True   True   True
3  True   True   True
4  True  False   True

In [80]:
df['noshow']=df.sum(axis=1)==0#setting the df.sum to equal zero finds all "0's" and returns a TRUE value to caluclate the probability
df.head()

0      1      2  noshow
0  True   True  False   False
1  True  False   True   False
2  True   True   True   False
3  True   True   True   False
4  True  False   True   False

In [81]:
df.noshow.mean()

0.02675

## How likely is it that a food truck will show up sometime this week?

In [82]:
nrows = 100_000
ncols = 5# number of days in the week (M-F)
outcomes = [True, False] #True = show & False = noshow
#run sim
seen = np.random.choice(outcomes, nrows*ncols, p=[.7,.3]).reshape(nrows,ncols)#note "p" --- "probaibility". It is set at 70/30
seen
#build the df
df = pd.DataFrame(seen)
df.head()
df['noshow']=df.sum(axis=1)==0#setting the df.sum to equal zero finds all "0's" and returns a TRUE value to caluclate the probability
df.head()
df.noshow.mean()

0.00248

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [87]:
nrows = 100_000
ncols = 23#number of people in the room
days = [r for r in range(366)]

bdays=np.random.choice(days, nrows*ncols).reshape(nrows,ncols)
bdays

array([[353, 256, 283, ..., 167, 298,  80],
       [102, 269,   8, ..., 250, 166,   7],
       [130, 310, 248, ..., 216, 350, 146],
       ...,
       [140,  99, 343, ..., 178, 226, 265],
       [ 61, 187, 314, ..., 126,  55, 353],
       [316, 308, 239, ...,  20, 290, 334]])

In [88]:
#build the df
df = pd.DataFrame(bdays)
df.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0  353  256  283    4  300  159  240   74  194  156  ...  352   87  325  176   
1  102  269    8  187  302  239  288  126  235  306  ...  275  335  114   84   
2  130  310  248  120  359  202  197  334  137  313  ...   91  235  133   25   
3   71   79   38  147  241  168  261  340  200  118  ...   43   42  364   11   
4   18   40  348  144  172  230  288    8   10   86  ...   23  199  352  315   

    17   18   19   20   21   22  
0   50  119  248  167  298   80  
1   36    9  165  250  166    7  
2  236   41  342  216  350  146  
3   43   35  151   56  318  141  
4  167  105  211  266    9  196  

[5 rows x 23 columns]

In [95]:
df['same_bday']=df.nunique(axis=1) == ncols-1#"nunique" finds the same two numbers column by column equal to "ncols-1"
df.head()

0    1    2    3    4    5    6    7    8    9  ...   14   15   16   17  \
0  353  256  283    4  300  159  240   74  194  156  ...   87  325  176   50   
1  102  269    8  187  302  239  288  126  235  306  ...  335  114   84   36   
2  130  310  248  120  359  202  197  334  137  313  ...  235  133   25  236   
3   71   79   38  147  241  168  261  340  200  118  ...   42  364   11   43   
4   18   40  348  144  172  230  288    8   10   86  ...  199  352  315  167   

    18   19   20   21   22  same_bday  
0  119  248  167  298   80      False  
1    9  165  250  166    7      False  
2   41  342  216  350  146      False  
3   35  151   56  318  141      False  
4  105  211  266    9  196      False  

[5 rows x 24 columns]

In [97]:
df.same_bday.mean()

0.11794

### 20 people

In [98]:
nrows = 100_000
ncols = 20#number of people in the room
days = [r for r in range(366)]

bdays=np.random.choice(days, nrows*ncols).reshape(nrows,ncols)
bdays

df = pd.DataFrame(bdays)
df.head()
df['same_bday']=df.nunique(axis=1) == ncols-1#"nunique" finds the same two numbers column by column equal to "ncols-1"
df.head()
df.same_bday.mean()

0.32365

### 40 people

In [99]:
nrows = 100_000
ncols = 20#number of people in the room
days = [r for r in range(366)]

bdays=np.random.choice(days, nrows*ncols).reshape(nrows,ncols)
bdays

df = pd.DataFrame(bdays)
df.head()
df['same_bday']=df.nunique(axis=1) == ncols-1#"nunique" finds the same two numbers column by column equal to "ncols-1"
df.head()
df.same_bday.mean()

0.32213